# Generated by Django 2.0.7 on 2019-06-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'results',
            },
        ),
    ]
