# Generated by Django 2.0.7 on 2019-06-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='state',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='result',
            field=models.CharField(max_length=250),
        ),
    ]
