# Generated by Django 2.0.7 on 2019-06-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0002_auto_20190628_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='state',
        ),
    ]
