# Generated by Django 2.0.7 on 2019-06-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0004_hostlist_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='state',
        ),
    ]
