# Generated by Django 2.0.7 on 2019-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0006_hostlist_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='state',
            field=models.CharField(default='Running', max_length=50),
        ),
    ]
