# Generated by Django 2.0.7 on 2019-06-28 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0012_auto_20190628_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
