# Generated by Django 2.0.7 on 2019-07-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0013_auto_20190628_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostlist',
            options={'verbose_name': 'Report'},
        ),
        migrations.RenameField(
            model_name='hostlist',
            old_name='hostname',
            new_name='Hostname',
        ),
        migrations.RenameField(
            model_name='hostlist',
            old_name='result',
            new_name='Result',
        ),
        migrations.RenameField(
            model_name='hostlist',
            old_name='state',
            new_name='State',
        ),
        migrations.AddField(
            model_name='hostlist',
            name='Pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
