# Generated by Django 2.0.7 on 2019-07-16 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0014_auto_20190711_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(blank=True, max_length=500)),
                ('script', models.CharField(blank=True, max_length=500)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('DateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Scripts',
            },
        ),
    ]
