# Generated by Django 2.0.7 on 2019-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0015_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('sript_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Analytic',
            },
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
