# Generated by Django 2.0.7 on 2019-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0016_auto_20190723_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='SubmittedBy',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
