# Generated by Django 2.0.7 on 2019-08-22 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0017_hostlist_submittedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('Owner', models.CharField(default=' ', max_length=50)),
                ('DateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('HostCount', models.IntegerField()),
                ('State', models.CharField(default=' ', max_length=50)),
            ],
            options={
                'verbose_name': 'ScheduledJob',
            },
        ),
    ]
