# Generated by Django 2.0.7 on 2019-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0019_scheduledjobs_wf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='JobState',
            field=models.CharField(default='Running', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduledjobs',
            name='JobState',
            field=models.CharField(default='Running', max_length=50),
        ),
    ]
