# Generated by Django 2.0.7 on 2019-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0020_auto_20190823_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobs',
            name='NonSuccess_coount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledjobs',
            name='running_coount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledjobs',
            name='success_coount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduledjobs',
            name='HostCount',
            field=models.IntegerField(blank=True),
        ),
    ]
