# Generated by Django 2.0.7 on 2019-08-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0022_auto_20190826_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledjobs',
            old_name='NonSuccess_coount',
            new_name='NonSuccess_count',
        ),
        migrations.RenameField(
            model_name='scheduledjobs',
            old_name='success_coount',
            new_name='success_count',
        ),
    ]
