# Generated by Django 2.0.7 on 2019-08-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0023_auto_20190826_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobs',
            name='InValidHosts',
            field=models.IntegerField(default=0),
        ),
    ]
