# Generated by Django 2.0.7 on 2019-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0025_patch_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch_report',
            old_name='host_name',
            new_name='hostname',
        ),
        migrations.AddField(
            model_name='patch_report',
            name='Pid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patch_report',
            name='state',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
