# Generated by Django 2.0.7 on 2019-09-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0026_auto_20190916_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch_report',
            old_name='hostname',
            new_name='host_name',
        ),
    ]
