# Generated by Django 2.0.7 on 2019-09-16 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0027_auto_20190916_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch_report',
            old_name='state',
            new_name='post_cves_low',
        ),
        migrations.AddField(
            model_name='patch_report',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patch_report',
            name='State',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
